name: verify
channels:
  - conda-forge
dependencies:
  - python=3.12
  - cadet==5.0.3
  - pip
  - pip:
      - scipy
      - numpy
      - matplotlib
      - pytest
      - pandas
      - h5py
      - joblib
      - cadet-python==1.0.4
      - cadet-rdm
