name: CI

on:
  pull_request:
  push:
    branches:
      - main
  workflow_dispatch:
    inputs:
      docker_image:
        description: "Docker image to use for the verification job"
        required: false
        default: "ghcr.io/cadet/cadet-suite:master"

permissions:
  contents: read

jobs:
  verify:
    runs-on: ubuntu-latest
    env:
      DOCKER_IMAGE: ${{ github.event.inputs.docker_image || 'ghcr.io/cadet/cadet-suite:master' }}
      PYTEST_ARGS: ""
    steps:
      - name: Run test in Docker
        run: |
          docker pull "$DOCKER_IMAGE"
          docker run --rm \
            -e REPOSITORY="${{ github.repository }}" \
            -e COMMIT_SHA="${{ github.event.pull_request.head.sha || github.sha }}" \
            "$DOCKER_IMAGE" \
            bash -c "
              set -e

              echo \"Using CADET-Verification commit: \$COMMIT_SHA\"

              echo 'Creating and entering workspace...'
              mkdir -p /tmp/cadet-verification && cd /tmp/cadet-verification

              echo 'Cloning CADET-Verification'
              git clone https://github.com/cadet/CADET-Verification.git .
              git fetch origin \$COMMIT_SHA
              git checkout \$COMMIT_SHA

              echo 'Installing Python dependencies'
              pip install mpmath scipy numpy matplotlib pytest pandas h5py joblib

              echo 'Running verification'
              pytest -s \$PYTEST_ARGS src/verify_cadet-core.py
            "
