name: Verify CADET-Core

on:
  workflow_dispatch:
    inputs:
      docker_image:
        description: "Docker image to use"
        required: true
        default: "ghcr.io/cadet/cadet-suite:master"
      pytest_args:
        description: "Pytest CLI args"
        required: false
        default: ""

permissions:
  contents: write

jobs:
  verify:
    runs-on: ubuntu-latest
    env:
      DOCKER_IMAGE: ${{ github.event.inputs.docker_image }}
      PYTEST_ARGS: ${{ github.event.inputs.pytest_args }}

    steps:
      - name: Run test in Docker
        run: |
          docker pull "$DOCKER_IMAGE"
          docker run --rm \
            -e GITHUB_TOKEN="${{ secrets.GH_PAT }}" \
            -e PYTEST_ARGS="$PYTEST_ARGS" \
            -e EVENT_NAME="${{ github.event_name }}" \
            -e REPOSITORY="${{ github.repository }}" \
            "$DOCKER_IMAGE" \
            bash -c "
              set -e

              echo 'Extracting branch name from pytest args...'
              VERIFICATION_BRANCH=\$(echo \"\$PYTEST_ARGS\" | grep -oP '(?<=--branch-name=)[^ ]*')
              VERIFICATION_BRANCH=\${VERIFICATION_BRANCH:-main}
              echo \"Using CADET-Verification branch: \$VERIFICATION_BRANCH\"

              echo 'Creating and entering workspace...'
              mkdir -p /tmp/cadet-verification && cd /tmp/cadet-verification

              echo 'Installing keyring and setting up token'
              pip install keyring keyrings.alt

              echo '\${GITHUB_TOKEN}' | keyring set https://github.com cadet-bot

              echo 'Setting up Git credential helper'
              git config --global credential.helper store
              echo "https://cadet-bot:\$GITHUB_TOKEN@github.com" > ~/.git-credentials

              echo 'Configuring Git user'
              git config --global user.name 'cadet-bot'
              git config --global user.email 'cadet-bot@users.noreply.github.com'

              echo 'Cloning CADET-Verification'
              rdm clone https://github.com/cadet/CADET-Verification.git .
              git checkout \$VERIFICATION_BRANCH

              echo 'Installing Python dependencies'
              pip install mpmath scipy numpy matplotlib pytest pandas h5py joblib

              echo 'Running verification'
              pytest -s \$PYTEST_ARGS src/verify_cadet-core.py \
                --commit-message=\"CADET-Core verification via \$EVENT_NAME on \$(date +%F)\"

              echo 'Running rdm checks and pushing'
              rdm check
              rdm push
            "
